import { notFound } from 'next/navigation';
import Image from 'next/image';
import Link from 'next/link';
import { projects } from '@/data/projects';
import { projectSlug } from '@/data/project-utils';
import type { Metadata } from 'next';
export function generateStaticParams() { return projects.en.map((project) => ({ slug: projectSlug(project.title) })); }
export async function generateMetadata({ params }: { params: Promise<{ slug: string }> }): Promise<Metadata> { const { slug } = await params; const project = projects.en.find((item) => projectSlug(item.title) === slug); return project ? { title: `${project.title} | Zulfikar`, description: project.summary, alternates: { canonical: `/projects/${slug}` }, openGraph: { title: project.title, description: project.summary, images: project.screenshot ? [project.screenshot] : [] } } : {}; }
export default async function ProjectDetail({ params, searchParams }: { params: Promise<{ slug: string }>; searchParams: Promise<{ lang?: string }> }) {
 const { slug } = await params; const locale = (await searchParams).lang === 'id' ? 'id' : 'en'; const index = projects.en.findIndex((item) => projectSlug(item.title) === slug); if (index < 0) notFound(); const project = projects[locale][index];
 const labels = locale === 'id' ? ['Masalah', 'Solusi', 'Peran Saya', 'Arsitektur', 'Hasil', 'Status', 'Catatan Kerahasiaan'] : ['Problem', 'Solution', 'My Role', 'Architecture', 'Result', 'Status', 'Confidentiality Note']; const values = [project.problem, project.solution, project.role, project.architecture, project.impact, project.status, project.confidentiality].filter(Boolean) as string[];
 return <main className="min-h-screen bg-slate-950 px-4 py-16 text-white"><article className="mx-auto max-w-5xl"><Link href={`/projects?lang=${locale}`} className="text-cyan-300">← {locale === 'id' ? 'Semua proyek' : 'All projects'}</Link><p className="mt-10 text-sm font-bold uppercase text-cyan-300">{project.type}</p><h1 className="mt-3 text-5xl font-black">{project.title}</h1><p className="mt-6 text-lg leading-8 text-slate-300">{project.summary}</p>{project.screenshot ? <Image src={project.screenshot} alt={`${project.title} application screenshot`} width={1280} height={720} priority className="mt-8 aspect-video w-full rounded-3xl border border-white/10 object-cover object-top" /> : <div className="mt-8 rounded-3xl border border-white/10 bg-white/5 p-6"><h2 className="font-black text-cyan-200">Workflow</h2><ol className="mt-4 grid gap-3 sm:grid-cols-4">{project.workflow.map((step, i) => <li key={step} className="rounded-xl bg-white/5 p-3"><b>{i + 1}.</b> {step}</li>)}</ol></div>}<div className="mt-8 flex flex-wrap gap-3">{project.liveUrl && <a href={project.liveUrl} target="_blank" rel="noreferrer" className="rounded-xl bg-cyan-300 px-5 py-3 font-bold text-slate-950">Live Demo</a>}{project.githubUrl && <a href={project.githubUrl} target="_blank" rel="noreferrer" className="rounded-xl border border-white/20 px-5 py-3 font-bold">GitHub</a>}{project.backendGithubUrl && <a href={project.backendGithubUrl} target="_blank" rel="noreferrer" className="rounded-xl border border-white/20 px-5 py-3 font-bold">Backend GitHub</a>}</div><div className="mt-10 grid gap-5 md:grid-cols-2">{values.map((value, i) => <section key={labels[i]} className="rounded-3xl border border-white/10 bg-white/5 p-6"><h2 className="font-black text-cyan-200">{labels[i]}</h2><p className="mt-3 leading-7 text-slate-300">{value}</p></section>)}</div><section className="mt-5 rounded-3xl border border-white/10 bg-white/5 p-6"><h2 className="font-black text-cyan-200">{locale === 'id' ? 'Fitur & Tantangan' : 'Features & Challenges'}</h2><ul className="mt-4 grid gap-2 sm:grid-cols-2">{[...project.keyFeatures, ...(project.challenges ?? [])].map(value => <li key={value} className="rounded-xl bg-white/5 p-3">{value}</li>)}</ul><div className="mt-5 flex flex-wrap gap-2">{project.techStack.map(tech => <span key={tech} className="rounded-full bg-cyan-300/10 px-3 py-2 text-sm text-cyan-100">{tech}</span>)}</div></section></article></main>;
}
